### ISSUE TITLE
Lesson2: Basic Analytics 요약

### ISSUE THREAD

**Issue by dusskapark** [dusskapark/analytics101#1]
# Coursera Module 2 > Lesson 2 : Basic Analytics
## 스터디의 목적

![screen shot 2015-06-23 at 1 13 17 pm](https://cloud.githubusercontent.com/assets/4177529/8298899/b2ebc474-19aa-11e5-897d-46e95ed3633e.png)
- 일단 데이터라는 것이 너무 많다. (심할 정도로 많다.)
- 그래서 각 데이터의 의미를 이해하고 
- 사용자의 행동 및 경험을 파고드는 것이 필요하다. 
## 웹사이트의 데이터 수집
- 쿠키와 태그를 활용해서 수집한다. 

![screen shot 2015-06-23 at 1 16 15 pm](https://cloud.githubusercontent.com/assets/4177529/8298904/bfee6a6e-19aa-11e5-8701-7a444341de80.png)
## Pyramid model of web data

![screen shot 2015-06-23 at 12 44 15 pm](https://cloud.githubusercontent.com/assets/4177529/8298909/cf98b83e-19aa-11e5-9aca-06705c93e3e4.png)
- 웹 데이터는 피러미드 형태로 정보를 구성한다. 
- 피라미드 위로 올라갈수록 중요한 정보이다. 
- Hit
  - html/css 등 코드 레벨의 정보이다. 
  - hit은 이미지를 교체하거나 영상 임베드 등으로도 올라갈 수 있으므로 의미있는 지표가 아니다. 
- Visit
  - 일반적으로 생각하는 UV 이다. 
  - 누군지는 모르지만 Unique 한 사용자가 '방문' 한 경우. 
- Unique identified Visitors
  - 누군지 알고 있는 사용자가 언제 방문했고. 등 
  - LV(Login Vaule) 정도에 해당함.
- _DATA는 양이 적을수록 가치가 높다._ 
## 각 사업별로 중요한 데이터
- 사업의 규모에 따라서 쓸 수 있는 예산의 숫자가 작다. 
- 또는 서비스의 규모에 따라서 해야하는 행동의 차이가 있다.

![screen shot 2015-06-23 at 12 49 59 pm](https://cloud.githubusercontent.com/assets/4177529/8299021/c517be94-19ac-11e5-9779-745607df6e9d.png)
### 작은 사업자
- 초기 사업자는 Acquisition 이 가장 중요하다. 
  - 이유는 신규 사업자의 경우 외부에서 새로운 사용자를 끌고오는 것에 집중해야 하기 때문이다. 
  - 따라서 초기 현금을 효과적으로 활용할 수 있도록 지표를 관리해야 한다. 
- 따라서 Cost per acquisition 또는 New User acquisition cost (UAC)가 상당히 중요하다. 
- 상세하게는 아래와 같다. (CPA, CTR NewVisitsRate)

![screen shot 2015-06-23 at 12 42 44 pm](https://cloud.githubusercontent.com/assets/4177529/8298916/df141e5c-19aa-11e5-8540-87368001c3ae.png)
### 중간 규모 사업자
- 가장 중요한 것은 사용자의 행동 패턴(Behaivor) 이다. 
- 초기 단계가 넘은 사업의 경우는 내부 사용자를 분석하고 그에 맞는 서비스나 조치를 내려야 한다
  - 따라서 이탈율, 새션당 페이지 수(Page Depth), 구매 전환/이탈율 등 관련 지표를 관리해야 한다. 

![screen shot 2015-06-23 at 12 43 43 pm](https://cloud.githubusercontent.com/assets/4177529/8298918/f03d0946-19aa-11e5-98ae-f2a5b7bc396c.png)
### 대규모 사업자
- 대형 사업자의 경우는 수익 극대화가 가장 중요하다. 
- 목표전환율(ConversionRate)과 각종 지표를 관리해야 한다. 
  - 다만 5번의 Assisted Conversion은 따로 측정해야 하는 이유를 잘 모르겠다. 
  - (뜻은 2개이상의 마케팅 체널에 노출된 경우, 각각의 컨버전을 잡는 것인데... 뭔 의미가 있는 것인지?)

![screen shot 2015-06-23 at 1 07 24 pm](https://cloud.githubusercontent.com/assets/4177529/8298920/fdaf6ce0-19aa-11e5-89b4-bbcf6711d5ac.png)

**Comment by SeongUgJung** [comment]
[위키페이지 02. Lesson 2 Base Analytics](https://github.com/dusskapark/analytics101/wiki/02.-Lesson-2-Base-Analytics)로 이동할게요~
