### ISSUE TITLE
Module2 > Lesson 3: An Introduction To Web Analytics Tools

### ISSUE THREAD

**Issue by dusskapark** [dusskapark/analytics101#3]
# Lesson  3 An Introduction To Web Analytics Tools,
## Analytics의 3가지 카테고리

![screen shot 2015-06-27 at 5 55 35 pm](https://cloud.githubusercontent.com/assets/4177529/8392291/b2c84052-1d20-11e5-93f0-c4c36f2492fc.png)
### 고급) 기업용 패키지
- 기업용 유료 Analytics 툴이 많지만 비싸다. 

![screen shot 2015-06-27 at 5 56 33 pm](https://cloud.githubusercontent.com/assets/4177529/8392295/c3f7b894-1d20-11e5-8d2f-b99f8e21f2f3.png)
### 중급) Point Solutions

![screen shot 2015-06-27 at 5 57 12 pm](https://cloud.githubusercontent.com/assets/4177529/8392296/d0301db8-1d20-11e5-963b-33d7f6855ad5.png)
- Analytics는 마케팅의 다양한 숙제들를 풀어내는데 실마리를 제공한다.
  1. 마케팅 성과 측정 또는 AB테스팅 등 
  2. Attribution 모델 (First, Linear, Last)
  3. 사이트 최적화
  4. 미디어 최적화 
### 초급) Analytics 가젯
- 클릭스트림 애널리틱스, 수익 애널리틱스 등 간단한 수준의 애널리틱스
  - 예) 야후 웹 애널리시스, 구글 애널리틱스, 몽구스 매트릭 등
- 공짜 또는 매우 저가로 제공함 
- 어떤 것이 가장 자신의 비즈니스에 도움이 되는지를 잘 파악해야 한다. 

---
## 비즈니스 사이즈 별 분석도구 사용 우선순위

![screen shot 2015-06-27 at 9 50 31 pm](https://cloud.githubusercontent.com/assets/4177529/8392299/e839fad2-1d20-11e5-8963-a6b710fd306f.png)

다른 분석도구도 중요하지만 특히나 중요한 것이 각 비즈니스별로 있다.
- 소기업: ClickStream Analytics 
- 중기업: 수익보고서 
- 대기업: VOC 
### Anlytics Gadgets

![screen shot 2015-06-27 at 10 07 43 pm](https://cloud.githubusercontent.com/assets/4177529/8392307/4b43b5dc-1d21-11e5-99f2-61299303b58a.png)
## No tool is ever as valuable as the analyst.

툴은 데이터를 수집하고 정보를 주지만, 분석가가 하는 일이 더 중요하다. 

---

**Comment by SeongUgJung** [comment]
[위키페이지 03. Lessone 3 웹 분석 툴 소개](https://github.com/dusskapark/analytics101/wiki/03.-Lessone-3-%EC%9B%B9-%EB%B6%84%EC%84%9D-%ED%88%B4-%EC%86%8C%EA%B0%9C)로 이동
